name: Build and Deploy

on:
  push:
    branches:
      - issue/3
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  update-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup for github actions
        run: |
          sed -i -e "2i  basePath: '/kokoichi-portfolio',\n" next.config.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build and export as a static file
        run: npm run export
      # Update gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
